@echo off
echo Starting NeuroGuard Microservices and Frontend...

echo Starting Eureka Server...
start "Eureka Server" cmd /k "cd /d neuroguard-backend\eureka-server && mvn spring-boot:run"

echo Waiting 10 seconds for Eureka to initialize...
timeout /t 10 /nobreak >nul

echo Starting Gateway Service...
start "Gateway Service" cmd /k "cd /d neuroguard-backend\gateway && mvn spring-boot:run"

echo Starting User Service...
start "User Service" cmd /k "cd /d neuroguard-backend\user-service && mvn spring-boot:run"

echo Starting Medical History Service...
start "Medical History Service" cmd /k "cd /d neuroguard-backend\medical-history-service && mvn spring-boot:run"

echo Starting Risk Alert Service...
start "Risk Alert Service" cmd /k "cd /d neuroguard-backend\risk-alert-service && mvn spring-boot:run"

echo Starting Product Order Service...
start "Product Order Service" cmd /k "cd /d neuroguard-backend\product-order-service && mvn spring-boot:run"

echo Starting Payment Service...
start "Payment Service" cmd /k "cd /d neuroguard-backend\payment-service && mvn spring-boot:run"

echo Starting Forums Service...
start "Forums Service" cmd /k "cd /d neuroguard-backend\forums-service && mvn spring-boot:run"

echo Starting Care Plan Service...
start "Care Plan Service" cmd /k "cd /d neuroguard-backend\careplan-service && mvn spring-boot:run"

echo Starting Prescription Service...
start "Prescription Service" cmd /k "cd /d neuroguard-backend\prescription-service && mvn spring-boot:run"

echo Starting Pharmacy Service...
start "Pharmacy Service" cmd /k "cd /d neuroguard-backend\pharmacy-service && mvn spring-boot:run"

echo Starting Reservation Service...
start "Reservation Service" cmd /k "cd /d neuroguard-backend\reservation-service && mvn spring-boot:run"

echo Starting Assurance Service...
start "Assurance Service" cmd /k "cd /d neuroguard-backend\assurance-service && mvn spring-boot:run"

echo Starting Consultation Service...
start "Consultation Service" cmd /k "cd /d neuroguard-backend\consultation-service && mvn spring-boot:run"

echo Starting Monitoring Service...
start "Monitoring Service" cmd /k "cd /d neuroguard-backend\monitoring-service && mvn spring-boot:run"

echo Starting Wellbeing Service...
start "Wellbeing Service" cmd /k "cd /d neuroguard-backend\wellbeing-ms\wellbeing-service && mvn spring-boot:run"

echo Starting ML Predictor Service...
start "ML Predictor Service" cmd /k "cd /d neuroguard-backend\ml-predictor-service && set EUREKA_ENABLED=true && python app.py"

echo Starting Angular Frontend...
start "Angular Frontend" cmd /k "cd /d FrontEnd && ng serve"

echo All services have been launched in separate windows!
pause
