spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: pharmacy-service
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacydb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: XDkzF2YNPA/7vXmPYJmaACjY6VBhwHJbr4pzPF5jguE=

neuroguard:
  sms:
    enabled: ${SMS_ENABLED:true}
    base-url: ${SMS_BASE_URL:https://api.twilio.com/2010-04-01/Accounts}
    account-sid: ${SMS_ACCOUNT_SID:}
    auth-token: ${SMS_AUTH_TOKEN:}
    from-number: ${SMS_FROM_NUMBER:+19788434209}
    default-country-prefix: ${SMS_DEFAULT_COUNTRY_PREFIX:+216}

logging:
  level:
    com.neuroguard: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
server:
  port: ${PHARMACY_SERVICE_PORT:8086}
