spring:
  application:
    name: risk-alert-service

  datasource:
    url: jdbc:mysql://localhost:3306/risk_alert_db?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: XDkzF2YNPA/7vXmPYJmaACjY6VBhwHJbr4pzPF5jguE=   # matches user-service # same as user-service

logging:
  level:
    com.neuroguard.riskalertservice: DEBUG
    org.springframework.security: DEBUG
ml:
  service:
    url: http://localhost:5000   # URL of Python ML service