spring.application.name=wellbeing-service
server.port=8084

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/wellbeing_db?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Client Configuratio.n
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
